---
label: product
hide_body: true
fields:
- name: id
  type: text
  config:
    required: false
  label: id
- name: name
  type: text
  config:
    required: false
  label: name
- name: price
  type: number
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
  label: price
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
- name: image
  type: file
  config:
    maxSize: 64
  label: image
- name: product_url
  type: text
  config:
    required: false
  label: product_url
pages:
- content/pagetest.md
- content/products/cheddar_wheel.md
